GCN:
  n_epochs: 1000
  hidden_dim: 16
  batch_size: 2    
  node_dim: 1433  # 1433 for CORA, 120 for PPI, 500 for PubMed
  lr: !!float 1e-3 # to enforce float when loaded
  dropout: 0.5
  weight_decay: !!float 5e-4
  n_classes: 3 # 7 for CORA, 3 for Pubmed
  dataset: "Cora"   # should be PubMed, Cora or PPI
  HITS@K_positive_samples: 10   # It should be 1 according to the benchmark paper   
  HITS@K_negative_samples_factor: 1000
  HITS@K_rank: 1000   # if positive sample ranked lower than that, it fails
  negative_samples_factor: 4

  n_train: 0.7
  n_val: 0.2
  n_test: 0.1

