node_dim: 50  # 50 for PPI
n_epochs: 1000
weight_decay: !!float 0.0   # Authors said not needed
lr: !!float 5e-3
n_classes: 121 # 7 for CORA, 3 for Pubmed, 121 for PPI
dataset: "PPI"   # should be PubMed, Cora or PPI
n_heads_1: 4
n_heads_2: 6
hidden_dim: 256
dropout: 0.0  # Authors said no need for dropout
batch_size: 2

n_train: 20
n_val: 2
n_test: 2