backbone: GAT
head: EdgePrediction

n_epochs: 300
weight_decay: !!float 5e-4
lr: !!float 5e-4 # to enforce float when loaded
batch_size: 256

n_train: 0.7
n_val: 0.2
n_test: 0.1

GCN:
  dimensions: [[1433, 300], [300, 100], [100, 50]]  # initial node dim is 1433 for CORA, 120 for PPI, 500 for PubMed
  dropout: 0.5


n_classes: 3 # 7 for CORA, 3 for Pubmed
dataset: "Cora"   # should be PubMed, Cora or PPI
HITS@K_positive_samples: 500   # It should be 1 according to the benchmark paper. For unexplained reason going above 500 caused memory leaks.
HITS@K_negative_samples_factor: 1000
HITS@K_rank: 1000   # if positive sample ranked lower than that, it fails
negative_samples_factor: 4



GAT:
  n_heads: [8, 8]
  dimensions: [[1433, 50], [400, 50]]


EdgePrediction:
  embedding_dim: 400