n_epochs: 150
weight_decay: !!float 1e-4
lr: !!float 1e-2 # to enforce float when loaded
batch_size: 64

n_classes: 7 # 7 for CORA, 3 for Pubmed
dataset: "Cora"   # should be PubMed, Cora or PPI

dimensions: [[1433, 70], [70, 7]]  # initial node dim is 1433 for CORA, 120 for PPI, 500 for PubMed
dropout: 0.5